"use strict";
// Auto-generated oracle module for: Maze.sb3
// Generated by oracle_generator.js
// DO NOT EDIT — regenerate by running oracle_generator.js

// cameraSystem: true — SpatialBounds oracle is suppressed for this project.
const CAMERA_SYSTEM = false;

const ORACLES = [
  {
    tier: 2,
    name: "Monotonic_Index",
    description: "\"Index\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Index", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Index decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 2,
    name: "StateEnum_Don_t_Update",
    description: "\"Don't Update?\" should only take values: false, true",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("Don't Update?", "");
  if (!v) return { violated: false };
  const allowed = ["false","true"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `Don't Update? = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_Touching_Color",
    description: "\"Touching Color?\" should only take values: true, false",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("Touching Color?", "");
  if (!v) return { violated: false };
  const allowed = ["true","false"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `Touching Color? = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_Key_Pressed",
    description: "\"Key Pressed?\" should only take values: false, true",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("Key Pressed?", "");
  if (!v) return { violated: false };
  const allowed = ["false","true"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `Key Pressed? = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 3,
    name: "LLM_The_program_enforces_a_strict_state_prog",
    description: "The program enforces a strict state progression where exactly one of Boot, Playing, or GameOver is active at any given time.",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const stateVar = stage.lookupVariableByNameAndType("State", "");
  if (!stateVar) return { violated: false };
  const validStates = ["Boot", "Playing", "GameOver"];
  return { violated: !validStates.includes(String(stateVar.value)) };
},
  },
  {
    tier: 3,
    name: "LLM_The_logo_end_broadcast_functions_exclusi",
    description: "The logo end broadcast functions exclusively as the signal that concludes the Boot phase and initiates the Playing phase.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_The_win_broadcast_functions_exclusively_",
    description: "The win broadcast functions exclusively as the signal that concludes the Playing phase and initiates the GameOver phase.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_The_Character_sprite_s_movement_routines",
    description: "The Character sprite's movement routines and collision evaluation scripts only execute when the game is actively in the Playing state.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
  {
    tier: 3,
    name: "LLM_A_Key_sprite_that_overlaps_with_the_Char",
    description: "A Key sprite that overlaps with the Character is immediately marked as collected and permanently excluded from further collision validation for the remainder of that round.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
  {
    tier: 3,
    name: "LLM_The_Key_Press_sprite_only_routes_input_e",
    description: "The Key Press sprite only routes input events or triggers gameplay actions while the Playing state is active to prevent invalid commands during non-playable phases.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
  {
    tier: 3,
    name: "LLM_All_collision_detection_logic_and_broadc",
    description: "All collision detection logic and broadcast listeners on the Character and Key sprites are strictly gated by the current game state to prevent spurious interactions between phases.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
];

module.exports = { ORACLES, CAMERA_SYSTEM };