"use strict";
// Auto-generated oracle module for: Maze.sb3
// Generated by oracle_generator.js
// DO NOT EDIT — regenerate by running oracle_generator.js

// cameraSystem: true — SpatialBounds oracle is suppressed for this project.
const CAMERA_SYSTEM = false;

const ORACLES = [
  {
    tier: 2,
    name: "Monotonic_Index",
    description: "\"Index\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Index", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Index decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 3,
    name: "LLM_Based_on_the_provided_program_structure_",
    description: "Based on the provided program structure and inferred logic, here are 6 properties that should always be true while the program runs:",
    check: (vm) => { try { const stage = vm.runtime?.getTargetForStage(); if (!stage || !stage.variables) return { violated: false }; const getVar = (key) => { const v = stage.variables[key]; if (!v) return undefined; return v.list ? v.list : v.value; }; const stat = getVar('CURRENT PLAYER STAT'); if (stat !== undefined && !['hided', 'discovered', 'saved', 'found'].includes(stat)) return { violated: true, message: `Invalid CURRENT PLAYER STAT value: ${stat}` }; const menu = getVar('MENU'); if (menu !== undefined && !['Main', 'In-Game', 'Game-End', 'Editor', 'Load Paths', 'Play Settings'].includes(menu)) return { violated: true, message: `Invalid MENU value: ${menu}` }; return { violated: false }; } catch (e) { return { violated: false }; } },
  },
  {
    tier: 3,
    name: "LLM_The_game_logic_maintains_exactly_one_act",
    description: "The game logic maintains exactly one active state from the set {Boot, Playing, GameOver} at any given instant.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
  {
    tier: 3,
    name: "LLM_The_Character_sprite_processes_direction",
    description: "The Character sprite processes directional movement inputs only when the system is in the Playing state.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
  {
    tier: 3,
    name: "LLM_The_collision_event_between_the_Characte",
    description: "The collision event between the Character sprite and the Key sprite is the mandatory trigger required to end the current round.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
  {
    tier: 3,
    name: "LLM_The_broadcast_of_the_win_message_signifi",
    description: "The broadcast of the \"win\" message signifies the definitive transition from the Playing state to the GameOver state.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
  {
    tier: 3,
    name: "LLM_The_initialization_of_the_Playing_state_",
    description: "The initialization of the Playing state is dependent on the prior processing of the \"logo end\" broadcast.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
  {
    tier: 3,
    name: "LLM_The_Key_sprite_and_Character_sprite_must",
    description: "The Key sprite and Character sprite must remain initialized and active in the game world to satisfy the program's collision detection requirements.",
    check: (vm) => { const targets = vm.runtime.targets || []; const key = targets.find(t => !t.isStage && t.getName() === 'Key'); const char = targets.find(t => !t.isStage && t.getName() === 'Character'); if (!key || !char) return { violated: true }; return { violated: false }; },
  },
];

module.exports = { ORACLES, CAMERA_SYSTEM };