"use strict";
// Auto-generated oracle module for: desert.sb3
// Generated by oracle_generator.js
// DO NOT EDIT — regenerate by running oracle_generator.js

// cameraSystem: true — SpatialBounds oracle is suppressed for this project.
const CAMERA_SYSTEM = false;

const ORACLES = [
  {
    tier: 2,
    name: "Monotonic_Recovered_health",
    description: "\"Recovered health\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Recovered health", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Recovered health decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 2,
    name: "Monotonic_Damage",
    description: "\"Damage\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Damage", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Damage decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 2,
    name: "Monotonic_Water",
    description: "\"Water\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Water", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Water decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 3,
    name: "LLM_The_game_state_machine_always_progresses",
    description: "The game state machine always progresses linearly through Boot, Playing, and GameOver without bypassing or reverting states during standard execution cycles.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
  {
    tier: 3,
    name: "LLM_The_Health_variable_is_initialized_to_4_",
    description: "The Health variable is initialized to -4 and is exclusively modified through predefined collision events, scripted interactions, or state transition routines.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_The_Recovered_health_variable_is_initial",
    description: "The Recovered health variable is initialized to 0 and only increments when explicitly triggered by designated game mechanics during the Playing state.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_The_estop_broadcast_is_solely_utilized_t",
    description: "The `estop` broadcast is solely utilized to signal round termination or GameOver conditions, ensuring a deterministic exit from the Playing state.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
  {
    tier: 3,
    name: "LLM_Collision_detection_between_the_Player_a",
    description: "Collision detection between the Player and Water sprites is evaluated continuously during gameplay and processes its associated logic exactly once per distinct contact to prevent duplicate state modifications.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_All_sprite_initializations_variable_assi",
    description: "All sprite initializations, variable assignments, and state validations are completed during the Boot phase before the program permits entry into the Playing state.",
    check: (vm) => ({ violated: false }) // generation failed,
  },
];

module.exports = { ORACLES, CAMERA_SYSTEM };