"use strict";
// Auto-generated oracle module for: has.sb3
// Generated by oracle_generator.js
// DO NOT EDIT — regenerate by running oracle_generator.js

// cameraSystem: true — SpatialBounds oracle is suppressed for this project.
const CAMERA_SYSTEM = true;

const ORACLES = [
  {
    tier: 2,
    name: "Monotonic_Rescue_streak",
    description: "\"Rescue streak:\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Rescue streak:", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Rescue streak: decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 2,
    name: "Monotonic_Total_Players_found",
    description: "\"Total Players found:\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Total Players found:", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Total Players found: decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 2,
    name: "Monotonic_Your_total_rescues",
    description: "\"Your total rescues:\" should never decrease",
    check: (() => {
  let _prev = null;
  return (vm) => {
    const stage = vm.runtime.getTargetForStage();
    if (!stage) return { violated: false };
    const v = stage.lookupVariableByNameAndType("Your total rescues:", "");
    if (!v) return { violated: false };
    const current = parseFloat(v.value);
    if (_prev !== null && !isNaN(current) && !isNaN(_prev) && current < _prev - 0.001) {
      const d = `Your total rescues: decreased: ${_prev} → ${current}`;
      _prev = current;
      return { violated: true, detail: d };
    }
    if (!isNaN(current)) _prev = current;
    return { violated: false };
  };
})(),
  },
  {
    tier: 2,
    name: "Countdown_NonNegative",
    description: "\"COUNT\" should not go below 0 during normal play",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("COUNT", "");
  if (!v) return { violated: false };
  const vc = stage.lookupVariableByNameAndType("SEEKER IS COUNTING?", "");
  const counting = vc && (vc.value === "true" || vc.value === true);
  const count = parseFloat(v.value);
  if (counting && count < -5) {
    return { violated: true, detail: `COUNT underflowed to ${count} during countdown` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_EDITOR",
    description: "\"EDITOR?\" should only take values: false, true",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("EDITOR?", "");
  if (!v) return { violated: false };
  const allowed = ["false","true"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `EDITOR? = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_LOADED_PATHS",
    description: "\"LOADED PATHS?\" should only take values: false, true",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("LOADED PATHS?", "");
  if (!v) return { violated: false };
  const allowed = ["false","true"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `LOADED PATHS? = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_AUDIO",
    description: "\"AUDIO\" should only take values: ON, SFX, OFF",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("AUDIO", "");
  if (!v) return { violated: false };
  const allowed = ["ON","SFX","OFF"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `AUDIO = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_SEEKER",
    description: "\"SEEKER\" should only take values: Player, Bot",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("SEEKER", "");
  if (!v) return { violated: false };
  const allowed = ["Player","Bot"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `SEEKER = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_MAP",
    description: "\"MAP\" should only take values: Custom, Standard",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("MAP", "");
  if (!v) return { violated: false };
  const allowed = ["Custom","Standard"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `MAP = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_MENU",
    description: "\"MENU\" should only take values: Load Paths, Editor, In-Game, Game-End, Main, Play Settings",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("MENU", "");
  if (!v) return { violated: false };
  const allowed = ["Load Paths","Editor","In-Game","Game-End","Main","Play Settings"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `MENU = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_SEEKER_IS_COUNTING",
    description: "\"SEEKER IS COUNTING?\" should only take values: true, false",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("SEEKER IS COUNTING?", "");
  if (!v) return { violated: false };
  const allowed = ["true","false"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `SEEKER IS COUNTING? = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StateEnum_CURRENT_PLAYER_STAT",
    description: "\"CURRENT PLAYER STAT\" should only take values: hided, discovered, saved, found",
    check: (vm) => {
  const stage = vm.runtime.getTargetForStage();
  if (!stage) return { violated: false };
  const v = stage.lookupVariableByNameAndType("CURRENT PLAYER STAT", "");
  if (!v) return { violated: false };
  const allowed = ["hided","discovered","saved","found"];
  const cur = String(v.value);
  if (!allowed.includes(cur)) {
    return { violated: true, detail: `CURRENT PLAYER STAT = "${cur}" — not in allowed set: ${allowed.join(", ")}` };
  }
  return { violated: false };
},
  },
  {
    tier: 2,
    name: "StaticBug_AliasingVariables",
    description: "14 variable IDs shared across sprites — writes in one sprite corrupt another",
    check: (() => {
  let _reported = false;
  return (vm) => {
    if (_reported) return { violated: false };
    _reported = true;
    return { violated: true, detail: "14 variable IDs shared across sprites — writes in one sprite corrupt another" + " Examples: " + "Player.hidden for seeker? = Bot1.hidden for seeker?; Player.power = Bot1.power; Player.speed up = Bot1.speed up" };
  };
})(),
  },
  {
    tier: 3,
    name: "LLM_The_game_state_must_always_remain_within",
    description: "The game state must always remain within the valid set of defined values: Boot, Initialising, Menu, Playing, or GameOver.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
  {
    tier: 3,
    name: "LLM_Score_and_statistic_variables_such_as_Hi",
    description: "Score and statistic variables such as 'Highest rescue streak', 'Total Players found', 'Your total rescues', 'Rescue streak', 'Meters walked', and 'Stealth meters' must never decrease during runtime.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
  {
    tier: 3,
    name: "LLM_Sprite_coordinate_values_are_considered_",
    description: "Sprite coordinate values are considered valid regardless of whether they lie inside or outside the 480×360 stage viewport due to the intentional virtual camera panning system.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_All_14_shared_variable_IDs_maintain_imme",
    description: "All 14 shared variable IDs maintain immediate global consistency, meaning any assignment to a shared variable instantly updates its value for all sprites referencing that ID.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_The_game_loop_must_continuously_broadcas",
    description: "The game loop must continuously broadcast tick messages every frame to drive logic updates for critical sprites including the Player, Bots, Level, Path, and Spots.",
    check: (vm) => ({ violated: false }),
  },
  {
    tier: 3,
    name: "LLM_The_MENU_variable_must_synchronize_with_",
    description: "The 'MENU' variable must synchronize with the active gameplay flow, holding values like 'In-Game' when the Playing state is active.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
  {
    tier: 3,
    name: "LLM_Collision_detection_logic_must_be_active",
    description: "Collision detection logic must be actively evaluated between interactive sprites, including the Player, Level, Spots, Path, Spawn, and Bot entities.",
    check: (vm) => ({ violated: false }) // generation failed (invalid syntax),
  },
];

module.exports = { ORACLES, CAMERA_SYSTEM };